### ISSUE TITLE
Python 高版本语法特性的兼容性问题

### ISSUE THREAD

**Issue by fishyy119** [KJH-x/scans_creator#1]
### 1 - python3.8下运行，报错
```
Traceback (most recent call last):
  File "e:\y19\_\scans_creator\scan_creator.py", line 15, in <module>
    from VideoInfo import VideoInfo
  File "e:\y19\_\scans_creator\VideoInfo.py", line 5, in <module>
    class VideoInfo:
  File "e:\y19\_\scans_creator\VideoInfo.py", line 6, in VideoInfo
    def __init__(self, file_info: Dict[str, str | int], video_info: Dict, audio_info: Dict, subtitle_info: Dict):
TypeError: unsupported operand type(s) for |: 'type' and 'type' 
```

貌似这是更高版本才有的特性，3.8还不支持。

### 2 - f-string的问题
Python3.11下运行，报错（其实3.8下也报错，只不过是更加模糊的报错文本）
```
  File "e:\y19\_\scans_creator\scan_creator.py", line 532
    scan.save(f"scans/{datetime.now().strftime("%H%M%S")}.scan.{video_info.file_name}.png")
                                                ^
SyntaxError: f-string: unmatched '('
```
在我这那句要改成
```
scan.save(f'scans/{datetime.now().strftime("%H%M%S")}.scan.{video_info.file_name}.png')
```
才能运行的样子，即把最外面的双引号换成单引号避免与里面重复。

顺带一提这个报错貌似出现在代码解析的时候，但我的VSCode并没有提示，怪。

**Comment by KJH-x** [comment]
Union 的类型批注写法是在3.10之后引入的
 [PEP 604 – Allow writing union types as X | Y](https://peps.python.org/pep-0604/)
 [python doc: union-type](https://docs.python.org/3/library/stdtypes.html#union-type)

f-string 的嵌套用法是在3.12的更新后引入的：
[PEP 701 – Syntactic formalization of f-strings](https://peps.python.org/pep-0701/)
[python doc: f-strings](https://docs.python.org/3.12/reference/lexical_analysis.html#f-strings)

感谢你的issue，已经暂时对此在requirement上作修改:[5483cb8](https://github.com/KJH-x/scans_creator/commit/5483cb8c25c502c5b667abec326c3c07a873483d)，后续可能会对代码做兼容性修改

**Comment by KJH-x** [comment]
1. 删除Union类型批注不影响使用，但是为了开发的严谨性，不会发布此修改版，在3.8使用可以自行删除类型注释
2. 在[ed34eb6](https://github.com/KJH-x/scans_creator/commit/ed34eb626ee122e9fb06772b93c17141d8b2bd05)中，f-string 的嵌套被修复，目前的要求是python>=3.10.x
